replicaCount: 1

moodleUsername: admin
moodlePassword: YourStrongMoodlePass123
moodleEmail: admin@example.com

mariadb:
  enabled: false

externalDatabase:
  host: ${rds_endpoint}
  port: 3306
  user: admin
  password: ${rds_password}
  database: moodledb

persistence:
  enabled: true
  # storageClass: "gp3"  # Disabled: use static provisioning
  existingClaim: "moodle-static-pv-claim"
  size: 8Gi

service:
  type: LoadBalancer

ingress:
  enabled: false

livenessProbe:
  enabled: true
  httpGet:
    path: /login/index.php
    port: http
  exec: null
  tcpSocket: null
  initialDelaySeconds: 600
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 6

readinessProbe:
  enabled: true
  httpGet:
    path: /login/index.php
    port: http
  exec: null
  tcpSocket: null
  initialDelaySeconds: 30
  timeoutSeconds: 3
  periodSeconds: 5
  failureThreshold: 6
